# Generated by Django 6.1.1 on 2026-10-02 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artworks', '0004_alter_withdrawal_options_artwork_style_and_more'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm đánh giá')),
                ('comment', models.TextField(max_length=1000, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'CREATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ được đánh giá')),
                ('commission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='commissions.commission', verbose_name='Đơn đặt vẽ Commission')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='artworks.order', verbose_name='Đơn mua tác phẩm')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá nghệ sĩ',
                'verbose_name_plural': 'Danh sách đánh giá nghệ sĩ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề thông báo')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('notification_type', models.CharField(choices=[('ORDER_COMPLETED', 'Đơn mua hoàn tất'), ('CREATOR_SALE', 'Lượt mua tác phẩm mới'), ('COMMISSION_REQUESTED', 'Yêu cầu đặt vẽ mới'), ('COMMISSION_PROPOSAL', 'Báo giá Commission'), ('COMMISSION_PAID', 'Ký quỹ thành công'), ('COMMISSION_DELIVERED', 'Bàn giao phác thảo/tác phẩm'), ('COMMISSION_REVISION', 'Yêu cầu chỉnh sửa'), ('COMMISSION_COMPLETED', 'Nghiệm thu hoàn tất'), ('WITHDRAWAL_STATUS', 'Trạng thái rút tiền'), ('SYSTEM', 'Thông báo hệ thống')], default='SYSTEM', max_length=40, verbose_name='Loại thông báo')),
                ('target_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Đường dẫn đối tượng')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Mã tham chiếu (chống trùng)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Danh sách thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
