# Generated by Django 6.1.1 on 2026-10-02 11:25

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Mã đặt vẽ')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề yêu cầu')),
                ('description', models.TextField(verbose_name='Mô tả ý tưởng / Brief')),
                ('license_type', models.CharField(choices=[('PERSONAL', 'Sử dụng cá nhân (Personal)'), ('COMMERCIAL', 'Sử dụng thương mại (Commercial)')], default='PERSONAL', max_length=20, verbose_name='Loại quyền sử dụng')),
                ('budget', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='Ngân sách dự kiến (VND)')),
                ('deadline', models.DateField(verbose_name='Hạn mong muốn hoàn thành')),
                ('reference_image', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\Admin\\Desktop\\ARTFAIR\\artfair_backend\\protected_media'), upload_to='commissions/references/%Y/%m/', verbose_name='Tệp tham khảo / Moodboard')),
                ('reference_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên tệp tham khảo')),
                ('reference_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Dung lượng tệp tham khảo (bytes)')),
                ('status', models.CharField(choices=[('REQUESTED', 'Chờ nghệ sĩ phản hồi'), ('QUOTED', 'Đã báo giá / Chờ duyệt'), ('IN_PROGRESS', 'Đang thực hiện'), ('DELIVERED', 'Đã bàn giao / Chờ nghiệm thu'), ('REVISION_REQUESTED', 'Yêu cầu chỉnh sửa'), ('COMPLETED', 'Hoàn tất / Đã giải ngân'), ('REJECTED', 'Nghệ sĩ từ chối'), ('CANCELLED', 'Đã hủy')], default='REQUESTED', max_length=25, verbose_name='Trạng thái')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá đã chốt (VND)')),
                ('agreed_delivery_date', models.DateField(blank=True, null=True, verbose_name='Hạn bàn giao đã chốt')),
                ('agreed_scope', models.TextField(blank=True, default='', verbose_name='Phạm vi công việc đã chốt')),
                ('agreed_terms', models.TextField(blank=True, default='', verbose_name='Điều khoản quyền đã chốt')),
                ('agreed_max_revisions', models.PositiveIntegerField(default=1, verbose_name='Số lần chỉnh sửa cho phép')),
                ('revisions_used', models.PositiveIntegerField(default=0, verbose_name='Số lần đã yêu cầu chỉnh sửa')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán mô phỏng (Ký quỹ)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thanh toán')),
                ('is_escrow_released', models.BooleanField(default=False, verbose_name='Đã giải ngân doanh thu cho nghệ sĩ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn tất')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Lý do nghệ sĩ từ chối')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Lý do hủy đơn')),
                ('sketch_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\Admin\\Desktop\\ARTFAIR\\artfair_backend\\protected_media'), upload_to='commissions/sketches/%Y/%m/', verbose_name='Phác thảo tiến độ')),
                ('sketch_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên tệp phác thảo')),
                ('final_delivery_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\Admin\\Desktop\\ARTFAIR\\artfair_backend\\protected_media'), upload_to='commissions/deliverables/%Y/%m/', verbose_name='Tệp bàn giao hoàn chỉnh')),
                ('final_delivery_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên tệp bàn giao')),
                ('final_delivery_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Dung lượng tệp bàn giao (bytes)')),
                ('final_delivery_note', models.TextField(blank=True, default='', verbose_name='Ghi chú bàn giao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo yêu cầu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Người mua (Buyer)')),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'CREATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='creator_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ nhận vẽ (Creator)')),
            ],
            options={
                'verbose_name': 'Đơn đặt vẽ (Commission)',
                'verbose_name_plural': 'Danh sách đặt vẽ (Commissions)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUEST_CREATED', 'Tạo yêu cầu đặt vẽ'), ('PROPOSAL_SENT', 'Nghệ sĩ gửi báo giá'), ('PROPOSAL_REJECTED', 'Người mua từ chối báo giá'), ('PAYMENT_COMPLETED', 'Thanh toán mô phỏng (Ký quỹ)'), ('SKETCH_UPLOADED', 'Tải lên phác thảo'), ('DELIVERED', 'Bàn giao tác phẩm'), ('REVISION_REQUESTED', 'Yêu cầu chỉnh sửa'), ('COMPLETED', 'Nghiệm thu hoàn tất'), ('REJECTED', 'Nghệ sĩ từ chối yêu cầu'), ('CANCELLED', 'Hủy yêu cầu')], max_length=30, verbose_name='Loại sự kiện')),
                ('title', models.CharField(max_length=150, verbose_name='Tiêu đề sự kiện')),
                ('note', models.TextField(blank=True, default='', verbose_name='Chi tiết sự kiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm diễn ra')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commissions.commission', verbose_name='Đơn đặt vẽ')),
            ],
            options={
                'verbose_name': 'Lịch sử sự kiện Commission',
                'verbose_name_plural': 'Lịch sử sự kiện Commission',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản báo giá')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='Báo giá chính thức (VND)')),
                ('delivery_date', models.DateField(verbose_name='Hạn dự kiến bàn giao')),
                ('scope_of_work', models.TextField(verbose_name='Phạm vi công việc')),
                ('max_revisions', models.PositiveIntegerField(default=1, verbose_name='Số lần chỉnh sửa cho phép')),
                ('license_terms', models.TextField(blank=True, default='', verbose_name='Điều khoản quyền sử dụng')),
                ('sketch_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\Admin\\Desktop\\ARTFAIR\\artfair_backend\\protected_media'), upload_to='commissions/proposals/%Y/%m/', verbose_name='Bản phác thảo đính kèm (nếu có)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ người mua duyệt'), ('ACCEPTED', 'Đã chấp nhận'), ('REJECTED', 'Người mua từ chối'), ('SUPERSEDED', 'Đã thay thế bằng báo giá mới')], default='PENDING', max_length=20, verbose_name='Trạng thái báo giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi báo giá')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commissions.commission', verbose_name='Đơn đặt vẽ')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ báo giá')),
            ],
            options={
                'verbose_name': 'Báo giá Commission',
                'verbose_name_plural': 'Danh sách báo giá Commission',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('commission', 'version'), name='unique_commission_proposal_version')],
            },
        ),
    ]
