# Generated by Django 6.1.1 on 2026-10-02 02:37

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên tag')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thẻ (Tag)',
                'verbose_name_plural': 'Thẻ (Tags)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tác phẩm')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug định danh')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả tác phẩm')),
                ('preview_image', models.ImageField(blank=True, help_text='Ảnh xem trước chất lượng trung bình, đã chèn watermark để bảo vệ bản quyền.', null=True, upload_to='previews/%Y/%m/', verbose_name='Ảnh xem trước (đã đóng watermark)')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã phát hành'), ('ARCHIVED', 'Đã lưu trữ')], default='DRAFT', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'CREATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ sở hữu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='artworks.category', verbose_name='Danh mục')),
                ('tags', models.ManyToManyField(blank=True, related_name='artworks', to='artworks.tag', verbose_name='Thẻ (Tags)')),
            ],
            options={
                'verbose_name': 'Tác phẩm nghệ thuật',
                'verbose_name_plural': 'Tác phẩm nghệ thuật',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\Admin\\.gemini\\antigravity\\scratch\\artfair_backend\\protected_media'), upload_to='original_files/%Y/%m/', verbose_name='Tệp bàn giao gốc')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Tên tệp gốc')),
                ('file_format', models.CharField(max_length=30, verbose_name='Định dạng tệp')),
                ('file_size_bytes', models.BigIntegerField(verbose_name='Dung lượng (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều rộng (pixels)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao (pixels)')),
                ('dpi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Độ phân giải DPI')),
                ('color_mode', models.CharField(blank=True, default='', max_length=30, verbose_name='Hệ màu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_file', to='artworks.artwork', verbose_name='Tác phẩm')),
            ],
            options={
                'verbose_name': 'Tệp gốc tác phẩm',
                'verbose_name_plural': 'Tệp gốc tác phẩm',
            },
        ),
        migrations.CreateModel(
            name='LicenseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('PERSONAL', 'Sử dụng cá nhân (Personal)'), ('COMMERCIAL', 'Sử dụng thương mại (Commercial)')], max_length=20, verbose_name='Loại quyền sử dụng')),
                ('price', models.DecimalField(decimal_places=0, help_text='Giá bán tối thiểu từ 1,000 VND trở lên.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='Giá bán (VND)')),
                ('terms', models.TextField(blank=True, default='', verbose_name='Điều khoản sử dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_options', to='artworks.artwork', verbose_name='Tác phẩm')),
            ],
            options={
                'verbose_name': 'Gói quyền sử dụng',
                'verbose_name_plural': 'Các gói quyền sử dụng',
                'ordering': ['license_type'],
                'constraints': [models.UniqueConstraint(fields=('artwork', 'license_type'), name='unique_artwork_license_type')],
            },
        ),
    ]
