# Generated by Django 6.1.1 on 2026-10-02 04:49

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\Admin\\Desktop\\ARTFAIR\\artfair_backend\\protected_media'), upload_to='original_files/%Y/%m/', verbose_name='Tệp bàn giao gốc'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('license_type', models.CharField(choices=[('PERSONAL', 'Sử dụng cá nhân (Personal)'), ('COMMERCIAL', 'Sử dụng thương mại (Commercial)')], max_length=20, verbose_name='Loại quyền sử dụng')),
                ('price_paid', models.DecimalField(decimal_places=0, help_text='Giá tiền được hệ thống xác thực và cố định tại thời điểm tạo đơn.', max_digits=12, verbose_name='Số tiền (VND)')),
                ('terms_snapshot', models.TextField(blank=True, default='', verbose_name='Điều khoản tại thời điểm mua')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('COMPLETED', 'Đã thanh toán (Thành công)'), ('FAILED', 'Thanh toán thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thanh toán')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='artworks.artwork', verbose_name='Tác phẩm')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
                ('license_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='artworks.licenseoption', verbose_name='Gói quyền')),
            ],
            options={
                'verbose_name': 'Đơn mua quyền sử dụng',
                'verbose_name_plural': 'Danh sách đơn mua',
                'ordering': ['-created_at'],
            },
        ),
    ]
