# Generated by Django 6.1.1 on 2026-10-02 07:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artworkfile_file_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='M? r?t ti?n')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='S? ti?n r?t (VND)')),
                ('status', models.CharField(choices=[('COMPLETED', '?? gi?i ng?n (M? ph?ng)'), ('PROCESSING', '?ang x? l? (M? ph?ng)'), ('REJECTED', 'T? ch?i')], default='COMPLETED', max_length=20, verbose_name='Tr?ng th?i')),
                ('note', models.CharField(blank=True, default='R?t doanh thu b?n quy?n s? d?ng t?c ph?m (M? ph?ng)', max_length=255, verbose_name='Ghi ch? giao d?ch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Th?i ?i?m t?o')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Ngh? s?')),
            ],
            options={
                'verbose_name': 'Y?u c?u r?t ti?n m? ph?ng',
                'verbose_name_plural': 'Danh s?ch r?t ti?n m? ph?ng',
                'ordering': ['-created_at'],
            },
        ),
    ]
