# Generated by Django 6.1.1 on 2026-10-02 14:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu rút tiền mô phỏng', 'verbose_name_plural': 'Danh sách rút tiền mô phỏng'},
        ),
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, default='', help_text='Ví dụ: Sơn dầu, Phục hưng, Tối giản, Anime, Digital Painting, Thủy mặc, Concept Art...', max_length=50, verbose_name='Phong cách nghệ thuật'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='Số tiền rút (VND)'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='note',
            field=models.CharField(blank=True, default='Rút doanh thu bán quyền sử dụng tác phẩm (Mô phỏng)', max_length=255, verbose_name='Ghi chú giao dịch'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Đã giải ngân (Mô phỏng)'), ('PROCESSING', 'Đang xử lý (Mô phỏng)'), ('REJECTED', 'Từ chối')], default='COMPLETED', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Mã rút tiền'),
        ),
        migrations.CreateModel(
            name='ArtworkFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm yêu thích')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='artworks.artwork', verbose_name='Tác phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tác phẩm yêu thích',
                'verbose_name_plural': 'Danh sách tác phẩm yêu thích',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'artwork'), name='unique_user_artwork_favorite')],
            },
        ),
    ]
